//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Childhood.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Child
    {
        public int ChildID { get; set; }
        public string ChildLastname { get; set; }
        public string ChildName { get; set; }
        public string ChildFathername { get; set; }
        public string ChildCityofResidence { get; set; }
        public string ChildHealthInsurancePolicy { get; set; }
        public int ChildParentID { get; set; }
        public string ChildAllergies { get; set; }
        public int ChildGroupID { get; set; }
        public byte[] ChildPhoto { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Parents Parents { get; set; }
    }
}
