//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Childhood.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parents()
        {
            this.Child = new HashSet<Child>();
        }
    
        public int ParentID { get; set; }
        public string ParentLastname { get; set; }
        public string ParentName { get; set; }
        public string ParentFathername { get; set; }
        public string ParentTelephoneNumber { get; set; }
        public int ParentNumPassportdata { get; set; }
        public int ParentSeriaPassportdata { get; set; }
        public string ParentEmaile { get; set; }
        public int ParentUserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Child> Child { get; set; }
        public virtual User User { get; set; }
    }
}
